name: Faster Whisper Transcription

on:
  push:
    paths:
      - 'videos/*.mp4'
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          pip install --upgrade pip
          pip install --no-cache-dir --force-reinstall faster-whisper ffmpeg-python


      - name: Transcribe and Translate Video
        run: |
          mkdir -p transcripts
          LATEST_VIDEO=$(ls -t videos/*.mp4 | head -n1)
          python transcribe.py "$LATEST_VIDEO"

      - name: Commit and Push Transcription
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add . || exit 0
          git commit -m "Added transcription for latest video" || exit 0
          git push
